[package]
name = "toy-db"
version = "0.1.0"
edition = "2018"
authors = ["Jerry Chen <jerry153fish@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "8.2.0"
